# Kubernetes manifests template for assets-manager deployment
# This is a template file that should be processed to replace placeholders with actual values
# 
# Placeholders to replace:
# - {{RESOURCE_TOKEN}} - Replace with actual resource token (e.g., "ib6mj")
# - {{CLIENT_ID}} - Replace with actual managed identity client ID
#


apiVersion: v1
kind: Namespace
metadata:
  name: assets-manager
---
# ConfigMap for shared configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: assets-manager-config
  namespace: assets-manager
data:
  AZURE_STORAGE_BLOB_CONTAINER_NAME: "assets"
  AZURE_SERVICEBUS_NAMESPACE: "sb{{RESOURCE_TOKEN}}" # Azure Spring Cloud library automatically appends the url suffix
  POSTGRESQL_SERVER_NAME: "psql{{RESOURCE_TOKEN}}"
  DATABASE_NAME: "assetsdb"
---
# Secret for sensitive configuration (will be populated from Key Vault)
apiVersion: v1
kind: Secret
metadata:
  name: assets-manager-secrets
  namespace: assets-manager
type: Opaque
data:
  # These will be populated from Key Vault using CSI driver
---
# Service Account for Managed Identity
apiVersion: v1
kind: ServiceAccount
metadata:
  name: assets-manager-sa
  namespace: assets-manager
  annotations:
    azure.workload.identity/client-id: "{{CLIENT_ID}}"
  labels:
    azure.workload.identity/use: "true"
---
# Web Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets-manager-web
  namespace: assets-manager
  labels:
    app: assets-manager-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assets-manager-web
  template:
    metadata:
      labels:
        app: assets-manager-web
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: assets-manager-sa
      containers:
      - name: web
        image: acr{{RESOURCE_TOKEN}}.azurecr.io/assets-manager-web:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: AZURE_CLIENT_ID
          value: "{{CLIENT_ID}}"
        - name: AZURE_STORAGE_ACCOUNT_NAME
          value: "st{{RESOURCE_TOKEN}}"
        - name: AZURE_STORAGE_BLOB_CONTAINER_NAME
          valueFrom:
            configMapKeyRef:
              name: assets-manager-config
              key: AZURE_STORAGE_BLOB_CONTAINER_NAME
        - name: AZURE_SERVICEBUS_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: assets-manager-config
              key: AZURE_SERVICEBUS_NAMESPACE
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://psql{{RESOURCE_TOKEN}}.postgres.database.azure.com:5432/assetsdb?sslmode=require"
        - name: SPRING_DATASOURCE_USERNAME
          value: "id{{RESOURCE_TOKEN}}"
        - name: SPRING_PROFILES_ACTIVE
          value: "azure"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
# Web Service
apiVersion: v1
kind: Service
metadata:
  name: assets-manager-web-service
  namespace: assets-manager
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: assets-manager-web
---
# Worker Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets-manager-worker
  namespace: assets-manager
  labels:
    app: assets-manager-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assets-manager-worker
  template:
    metadata:
      labels:
        app: assets-manager-worker
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: assets-manager-sa
      containers:
      - name: worker
        image: acr{{RESOURCE_TOKEN}}.azurecr.io/assets-manager-worker:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: AZURE_CLIENT_ID
          value: "{{CLIENT_ID}}"
        - name: AZURE_STORAGE_ACCOUNT_NAME
          value: "st{{RESOURCE_TOKEN}}"
        - name: AZURE_STORAGE_BLOB_CONTAINER_NAME
          valueFrom:
            configMapKeyRef:
              name: assets-manager-config
              key: AZURE_STORAGE_BLOB_CONTAINER_NAME
        - name: AZURE_SERVICEBUS_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: assets-manager-config
              key: AZURE_SERVICEBUS_NAMESPACE
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://psql{{RESOURCE_TOKEN}}.postgres.database.azure.com:5432/assetsdb?sslmode=require"
        - name: SPRING_DATASOURCE_USERNAME
          value: "id{{RESOURCE_TOKEN}}"
        - name: SPRING_PROFILES_ACTIVE
          value: "azure"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
# Worker Service (for internal monitoring)
apiVersion: v1
kind: Service
metadata:
  name: assets-manager-worker-service
  namespace: assets-manager
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: assets-manager-worker