CREATE USER "id4eis" WITH LOGIN;
GRANT ALL PRIVILEGES ON DATABASE assetsdb TO "id4eis";
GRANT ALL PRIVILEGES ON SCHEMA public TO "id4eis";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "id4eis";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "id4eis";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "id4eis";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "id4eis";
