CREATE USER "idwc123" WITH LOGIN;
GRANT ALL PRIVILEGES ON DATABASE assetsdb TO "idwc123";
GRANT ALL PRIVILEGES ON SCHEMA public TO "idwc123";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "idwc123";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "idwc123";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "idwc123";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "idwc123";
