spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none  # We're using schema.sql for schema definition
    # show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always  # Run schema.sql and data.sql on startup
      platform: oracle
      continue-on-error: true  # Set to true to continue despite errors
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      separator: ;  # Use semicolon as separator

server:
  port: 8080
