apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: assets-manager-kv-secrets
  namespace: assets-manager
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "ec2e3812-9b30-40da-9a3a-d246a6b2166e"
    keyvaultName: "kv-assetsmanager"
    tenantId: "de9dfb27-7122-49ec-8260-826003e96b9e"
    objects: |
      array:
        - |
          objectName: postgres-fqdn
          objectType: secret
        - |
          objectName: postgres-database
          objectType: secret
  secretObjects:
    - secretName: assets-manager-kv-secrets
      type: Opaque
      data:
        - objectName: postgres-fqdn
          key: postgres-fqdn
        - objectName: postgres-database
          key: postgres-database
