apiVersion: v1
kind: Service
metadata:
  name: assets-manager-web
  namespace: assets-manager
  labels:
    app: assets-manager-web
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: assets-manager-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
